[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2024-08-25"
components = ["rustfmt", "cargo", "clippy", "rust-analyzer", "llvm-tools-preview"]
profile = "default"
